fix: Exit on communication failure (#429)
fixes #430

Often when rerunning component creation, an error containing "Stream is
already completed, no further calls are allowed" comes up
```
Error rendering __main__.test_component
Traceback (most recent call last):
  File "/Users/josephnumainville/Documents/deephaven-core/.venv/lib/python3.10/site-packages/deephaven/ui/object_types/ElementMessageStream.py", line 159, in _render
    self._send_document_update(node, state)
  File "/Users/josephnumainville/Documents/deephaven-core/.venv/lib/python3.10/site-packages/deephaven/ui/object_types/ElementMessageStream.py", line 355, in _send_document_update
    self._connection.on_data(payload.encode(), new_objects)
  File "/Users/josephnumainville/Documents/deephaven-core/.venv/lib/python3.10/site-packages/deephaven_internal/plugin/object/__init__.py", line 47, in on_data
    self._wrapped.onData(payload, [javaify(ref) for ref in references])
RuntimeError: io.deephaven.plugin.type.ObjectCommunicationException: java.lang.IllegalStateException: Stream is already completed, no further calls are allowed
...
```

This doesn't need to raise an exception to the user as this is just the
previous component's message stream signaling it is closed, but it does
need to exit so it doesn't keep trying to hit the message stream.